# Generated by Django 4.1.2 on 2022-10-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("war", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="initial_status",
            field=models.JSONField(default={}),
        ),
    ]
