# Generated by Django 4.1.2 on 2022-10-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("war", "0003_alter_game_initial_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
